site_name: 'Enterprise-Scale-for-AKS'

nav:
  - Home: Secure-Baseline/README.md

plugins:
  - techdocs-core

# Uncomment to add extensions if desired
#markdown_extensions:
#  - markdown_inline_mermaid